import { HttpStatus } from '@nestjs/common';

export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',

  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_ACCOUNT_SUSPENDED',

  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_RATE_LIMITED = 'OTP_RATE_LIMITED',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PIN_ALREADY_SET = 'PIN_ALREADY_SET',
  PIN_LOCKED = 'PIN_LOCKED',

  INTEGRATION_ERROR = 'INTEGRATION_ERROR',
  INTEGRATION_TIMEOUT = 'INTEGRATION_TIMEOUT',
  INTEGRATION_UNAVAILABLE = 'INTEGRATION_UNAVAILABLE',
}

export const errorCodeToHttpStatus: Record<ErrorCode, HttpStatus> = {
  [ErrorCode.INTERNAL_ERROR]: HttpStatus.INTERNAL_SERVER_ERROR,
  [ErrorCode.VALIDATION_FAILED]: HttpStatus.BAD_REQUEST,
  [ErrorCode.RESOURCE_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.RESOURCE_ALREADY_EXISTS]: HttpStatus.CONFLICT,

  [ErrorCode.AUTH_TOKEN_MISSING]: HttpStatus.UNAUTHORIZED,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: HttpStatus.UNAUTHORIZED,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: HttpStatus.UNAUTHORIZED,
  [ErrorCode.AUTH_FORBIDDEN]: HttpStatus.FORBIDDEN,
  [ErrorCode.AUTH_ACCOUNT_SUSPENDED]: HttpStatus.FORBIDDEN,

  [ErrorCode.OTP_INVALID]: HttpStatus.BAD_REQUEST,
  [ErrorCode.OTP_EXPIRED]: HttpStatus.BAD_REQUEST,
  [ErrorCode.OTP_RATE_LIMITED]: HttpStatus.TOO_MANY_REQUESTS,

  [ErrorCode.USER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.PIN_ALREADY_SET]: HttpStatus.CONFLICT,
  [ErrorCode.PIN_LOCKED]: HttpStatus.FORBIDDEN,

  [ErrorCode.INTEGRATION_ERROR]: HttpStatus.BAD_GATEWAY,
  [ErrorCode.INTEGRATION_TIMEOUT]: HttpStatus.GATEWAY_TIMEOUT,
  [ErrorCode.INTEGRATION_UNAVAILABLE]: HttpStatus.SERVICE_UNAVAILABLE,
};
